sdl3: Change default value of `ibusSupport` to require `dbusSupport`
The old default causes android builds to fail because ibus support
is enabled while dbus support isn't:

```
$> nix eval nixpkgs#pkgsCross.aarch64-android.sdl3
error:
   … while calling a functor (an attribute set with a '__functor' attribute)
     at /nix/store/baym1k0gzm7kqix7vdp87v97hkxwilqx-source/lib/customisation.nix:306:7:
      305|     if missingArgs == { } then
      306|       makeOverridable f allArgs
         |       ^
      307|     # This needs to be an abort so it can't be caught with `builtins.tryEval`,

   … while evaluating a branch condition
     at /nix/store/baym1k0gzm7kqix7vdp87v97hkxwilqx-source/lib/customisation.nix:173:7:
      172|       in
      173|       if isAttrs result then
         |       ^
      174|         result

   (stack trace truncated; use '--show-trace' to show the full, detailed trace)

   error: SDL3 requires dbus support to enable ibus
```

To fix this this change makes the default value of `ibusSupport` depend
on the value of `dbusSupport`.